---
name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk:14.0.2-jdk-slim
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compile
        run: ./mvnw clean compile

      - name: unit test
        run: echo running unit test

      - name: integration test
        run: ./mvnw test

      - name: package artifact
        run: ./mvnw -Dmaven.test.skip=true package

      - name: deploy artifact
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Deploy
          token: ${{ secrets.PAT_TOKEN }}
