---
name: Deploy
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install deps
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install openjdk-14-jdk

      - name: build jar
        run: ./mvnw -Dmaven.test.skip=true package

      - name: push to docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: colinbut/github-actions-java-app
          tag_with_ref: true

      - name: push to github packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: colinbut1/github-actions-java-app/github-actions-java-app
          tag_with_ref: true
